version: '3'
services:
  backend:
    build: ./doctor-office-backend
    image: doctor-office-backend:latest   # Specify the image name here
    ports:
      - "5000:5000"
    env_file: 
      - ./doctor-office-backend/.env

  frontend:
    build: ./doctor-office-frontend
    image: doctor-office-frontend:latest  # Specify the image name here
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://backend:5000
